[PAT-1106] Prevent Jitsi from automatically refreshing the page after ending a session.
janeapp/video-chat pull request #147
Opened 2023-04-12 15:53 UTC by ivanjiang5628

## Description
- [Linear Ticket](https://linear.app/jane/issue/PAT-1106/prevent-jitsi-from-automatically-refreshing-the-page-after-ending-a)

- Adds `isJwtTokenExpired` function to determine if jwt has expired
- Prevent `PageReloadOverlay` from continuously reloading the page automatically if jwt has expired.

### Release Risk Assessment
Low Risk

### Demo Notes

## QA and Smoke Testing
### Steps to Reproduce
1. Create an jitsi online appt
2. Copy and paste the JWT from the video chat url onto jwt.io, and modify its expiration time to make it expire.
<img width="290" alt="image" src="https://user-images.githubusercontent.com/24568041/231876230-8663ea4e-7356-426b-b60a-b43785b7e423.png">

3. Use the expired jwt to open Jitsi app
4. We should see a error notification pops up and `connection` related errors in the console
<img width="536" alt="image" src="https://user-images.githubusercontent.com/24568041/231876490-b3bbbe76-5a78-4714-b851-d318b655d524.png">
<img width="755" alt="image" src="https://user-images.githubusercontent.com/24568041/231876603-44084e72-3f25-467f-b57e-fd96c234a4b1.png">
5. wait for a few minutes, and Jitsi app should no longer automatically reload the page after showing the jwt or connection-related errors.

extra QA: we probably need a smoke test to ensure this PR won't break anything before releasing it.

### Fixed / Expected Behaviour
Wait for a few minutes, and Jitsi app should no longer automatically reload the page after showing the jwt or connection-related errors.

### Other Considerations
> - Will this affect other parts of the app or views?
> - How can the success of this work be confirmed after release to production?
> - What QA have you already done?

## Screenshots
### Before
### After

2023-04-13 22:45 UTC, bitghost2m approved these changes
The code changes and logic looks good to me. 👍  just one comment.

2023-04-13 22:45 UTC, bitghost2m commented on react/features/base/jwt/functions.js
> +        return Date.now() >= jwtDecode(jwt).exp * 1000;
just want to double check if `jwtDecode(jwt).exp` returns `seconds` not `miliseconds`

2023-04-14 16:46 UTC, ivanjiang5628 commented on react/features/base/jwt/functions.js
> +        return Date.now() >= jwtDecode(jwt).exp * 1000;
Yea it returns `seconds` that's why we need to `*1000`

2023-04-14 16:48 UTC, ivanjiang5628 commented
## Test Plan

- [] We need to ensure that the Jitsi app no longer automatically reloads the page when seeing JWT or connection-related errors, such as an expired JWT.
- [] Quick smoke test of Jitsi telehealth (joining, functionality, etc.)

## Browsers

- [] Chrome
- [] Safari
- [] Firefox
- [] Android Chrome

## Pass PR in GitHub / Mark Scheduled for Release in Linear

- []  Mark as "Ready for Release"

2023-04-17 20:32 UTC, gregmoreno requested changes

2023-04-17 20:32 UTC, gregmoreno commented on react/features/base/jwt/functions.js
> +        return Date.now() >= jwtDecode(jwt).exp * 1000;
I'm late to the party but I suggest adding a comment why it is `1000`

2023-04-17 20:42 UTC, gregmoreno approved these changes

2023-04-18 17:18 UTC, merged