[TEL-282] Telehealth waiting area/ practitioner tool (ios)
janeapp/video-chat pull request #18
Opened 2020-09-11 20:48 UTC by ivanjiang5628

> **INSTRUCTIONS**
> Please make your PR readme as readable as possible. Only keep parts of this template that are filled out and meaningful to the reviewer.
>
> - Remove any quoted parts of the template below `>`. (These are just instructions for you to follow)
> - Remove any sections that are irrelevant.
> - Most importantly: explain the "WHY". Do your best to give the reviewer some context about this change.

## Description
> Provide a summary of the problem being solved, the work done, and what was added/removed/changed

- [Jira Ticket](https://janeapp.atlassian.net/browse/...)

### Risk / General PR Class
- [ ] 🔴 = High Risk
- [ ] 🔶 = Medium Risk
- [ ] 💚 = Low Risk
- [ ] 💜 = Almost Zero Risk
- [ ] 0️⃣ = Zero Risk

🐛 = Bug Fix (Fixes an Issue)
🌟 = New Feature (Adds Functionality)
🏇 = Performance improvement
👁 = UX / UI improvement
🏗 = Refactor
🌦 = Env Changes
☕️ = JS Dependency Changes
⚛️ = Jane Desktop Changes
💻 = Browser Refresh Required (Unobtrusive, Immediate, or Forced)

### Release Note
> Describe here a CS friendly version of what this fixes/adds. If the change is behind a feature flag, please include that in your description. If this is a hidden change CS doesn't need to really know about then just say so.

### Dependencies / ENV / Migrations / Client Reset
> Describe any migrations, dependencies or ENV variables that are required for this change. Add notes regarding the release such as rake tasks, libraries, or the need for a client reset. Notify the team, if they have to update their environment.

### Release Risk Assessment
> Describe what areas of Jane are touched by the change in this PR, and what it would look like if something were to go wrong, and how much damage could be done. Keep your neighborhood deployer in mind when filling in this section, it will help identify errant PRs more quickly during deploy.

### Demo Notes
> If you have instructions on how to demo, or a video/gif, add it here

## Code Review
Resource: [Dev Team Notion Page](https://www.notion.so/janeapp/Dev-Team-f06c6eb2ccca4066bc63fc1ac1bd2549)
Resource: [Code Review Checklist](https://www.notion.so/janeapp/Code-Review-checklist-2c510c527ac7470c902a5e8f25f9db3c)

- [ ] I clearly explained the WHY behind the work, in the Description above

#### Design
- [ ] I added instructions for how to test, in the QA section below
- [ ] I added tests for changes, or determined that none were required
- [ ] I demoed this to the appropriate person
- [ ] I considered both mobile & desktop views, or that wasn't relevant

#### Code
- [ ] I committed code with informative git messages
- [ ] I wrote readable code, or added comments if it was complex
- [ ] I performed a self-review of my own code
- [ ] I rebased my branch on the latest `master`
- [ ] I confirmed that all CircleCI tests are passing
- [ ] I didn't add new npm packages, or else I made damn sure the `yarn.lock` changes are safe for existing production packages

## QA and Smoke Testing
### Steps to Reproduce
> - Add steps on how to reproduce the problem and how to test
> - ie. Create Appointment > Clicked Arrived > Pay > Look for "this"

### Fixed / Expected Behaviour
> - What new behaviour does QA and Review need to look out for?

### Jane Desktop
> - Should these changes be tested in Jane Desktop? If the PR touches any of the [areas outlined here](https://www.notion.so/janeapp/Jane-Desktop-a10c9c06b180487982a3ef67d6163db9#9ea43281537e458089a87229e7281612), the answer is probably yes. If yes, indicate which areas.
> - How to test [video-chat inside Jane Desktop locally is outlined here](https://github.com/janeapp/jane_electron/blob/master/README.md#testing-video-chat)

### Other Considerations
> - Will this affect other parts of the app or views?
> - How can the success of this work be confirmed after release to production?
> - What QA have you already done?

## Screenshots
### Before
### After

2020-10-13 16:08 UTC, gerbus requested changes
Took a good look through the code here, generally looks great Ivan 👍 . I noticed a few things I thought should be addressed, and then also some thoughts/questions. Also, would love to see some screenshots of the new WaitingArea in the PR Writeup.

2020-10-13 17:02 UTC, ivanjiang5628 commented on react/features/toolbox/components/native/Toolbox.js
> +                {!_enableJaneWaitingAreaPage && <OverflowMenuButton
Sorry, I should have put the inVision mockup in this PR earlier
https://projects.invisionapp.com/share/S9YDMKLGWFQ#/screens/428100003

on the waiting area page, users can only test their audio/video devices so I hid the Chat/Hangup/OverflowMenu buttons.

2020-10-15 21:23 UTC, ivanjiang5628 commented on react/features/jane-waiting-area-native/index.js
> +import './reducer';
Hmm Seems like jitsi needs this file to inject the reducer to the global store....maybe we can keep it?

2020-10-19 21:40 UTC, ivanjiang5628 commented on react/features/large-video/components/LargeVideo.native.js
> +        _styles: ColorSchemeRegistry.get(state, 'LargeVideo'),
this `_styles` prop is from jitsi. probably we can keep it?

2020-10-20 15:19 UTC, gerbus approved these changes
Thanks for addressing all my feedback!

2020-11-02 16:08 UTC, gerbus commented
Hey @ivanjiang5628, just curious why there were more changes? Did this PR get demo'd to @markhazlett before going to code review?

2020-11-02 19:09 UTC, ivanjiang5628 commented
> Hey @ivanjiang5628, just curious why there were more changes? Did this PR get demo'd to @markhazlett before going to code review?

@gerbus Sorry for the confusion I need to update this PR for changing the waiting message UI and fix the legacy ios app compatibility issue. I also want to remove the polling from it so I converted this PR to `draft` and will request a code review again later.

2020-11-04 18:43 UTC, clem-jane commented
Thanks for not adding to this PR, @ivanjiang5628 
Let's keep a separate PR to add the newer changes instead of updating this PR.

2020-11-04 18:48 UTC, clem-jane commented
This was demoed with a Testflight build linked to s14. We should be able to QA with the same setup as well. 
The key areas demoed were the patient's view and practitioner's view of the Waiting Area. The buttons only function when both participants have arrived.

2020-12-04 22:26 UTC, jngo-janeapp commented
## Before Testing

- [ ] CI must be passing
- [ ] No conflicts
- [ ] No unresolved reviews/changes requested
- [ ] No additional changes/pushes from dev since the last round of QA
- [ ] Release note is sufficient for [#features](https://janeapp.slack.com/archives/C0KC1395G)
- [ ] Read through Notion / Jira story / Linear Issue / Slack Convo / Demo video

## Developer's Recommended Test Plan
- [ ] TBD

## Additional Thoughts on Testing
- [ ] TBD

## Mobile, Browsers, Jane Desktop

- [ ] Google Chrome
- [ ] Safari
- [ ] Firefox
- [ ] Microsoft Edge
- [ ] Jane Desktop
- [ ] iPad Mini
- [ ] iPhone

## Regression Testing / Exploratory

(Consider related areas or areas where data persists Ie. Chart Templates/Intake Forms, Chart Entries/Export to PDF, Reports / Export to CSV/xls, Payment / Receipts / Superbill(US))

- Can you export a PDF from this area/function?
- Can this functionality be reused somewhere else in Jane? Or does it share components with other areas in Jane. (Canadian & US Insurance)
- Does this area have an inverse setting? Enabled/Disabled, Beta Feature Flag
- Does this area have multiple setting types? Ie. Intake Forms, Permissions/Privacy, User types
- Does this correspond to an area in Online Booking? (Booking an appointment, Entering a credit card and paying for an appointment)
- Is this related to Payment Methods? Jane Payments: Stripe, Payfirma, Square Terminal, Cash, Gift Cards, Credit Memos, Account Credit, Packages
- Could this be affected by Family Relationships?
- Could data be affected by Merging Patient Profiles?
- Could data be affected by rebooking/canceling appointments or changing treatments?
- Can this be Created, Updated, Archived/Unarchived or Deleted? (CRUD Test)
- Activity Report?
- Trigger a validation Error?

## Peer Review for Moderate Risk or Higher
- [ ] Peer Review

## Pass Story on QA Board / Mark Done in Jira/ Mark Scheduled for Release in Linear
- [ ] LGTM 🚀

2021-03-25 15:33 UTC, jngo-janeapp commented
## Before Testing Thursday March 25th, 2021 
- [x] CI must be passing
- [x] No conflicts
- [x] No unresolved reviews/changes requested
- [x] No additional changes/pushes from dev since the last round of QA
- [x] Release note is sufficient for [#features](https://janeapp.slack.com/archives/C0KC1395G)
- [x] Read through Notion / Jira story / Linear Issue / Slack Convo / Demo video

## Developer's Recommended Test Plan
- [x] install Jane Online appointment QA iOS app( version 1.3.0(1)) with test flight.
- [x] Create an online appointment in Jane admin app in iOS safari/chrome -> go to the iOS video chat -> You will see the waiting area page.
- [x] Create an online appointment in Jane admin app -> Go to the video chat -> You will see the waiting area page.
- [x] When the patient opens the video chat app and is on the waiting area page, the practitioner-side video chat app will 
![Image from iOS (5)](https://user-images.githubusercontent.com/68558703/102154758-eec15f00-3e2e-11eb-98df-ffe8822648a9.png)
enable the admit button and the practitioner can see a client is waiting badge in the appointment panel in Jane admin app.
- [x] If the practitioner clicks on the admit button, the practitioner will join the call -> the patient-side video chat app will enable the begin button.
- [x] Then the patient can click the begin button to jump on the call and the video chat app will notify Jane that the patient has arrived.
- [x] When both participants are on the waiting area page:
- [x] If the practitioner leaves the waiting area -> the patient-side will not allow the patient to join the call and the begin button will be disabled.
- [x] If the patient leaves the waiting area -> the practitioner-side will not allow the practitioner to join the call and the Admit Client button will be disabled.
- [x] Older version IOS app compatibility:
- [x] If one participant is using the older version IOS app which doesn't include this waiting area feature update -> both the practitioner side and the patient side can start the video call by clicking the enabled begin/admit client button.

## Additional Thoughts on Testing
- [x] Ensure all buttons work as expected 

## Mobile, Browsers, Jane Desktop
- [x] iPad Mini
- [x] iPhone

## Peer Review for Moderate Risk or Higher
- [x] Peer Review

## Pass Story on QA Board / Mark Done in Jira/ Mark Scheduled for Release in Linear
- [x] LGTM 🚀

2021-03-25 16:18 UTC, jngo-janeapp commented
hey @ivanjiang5628 looks good on IOS !

2021-05-08 03:35 UTC, merged