[IMPT-348] Update screens for iOS welcome screen
janeapp/video-chat pull request #40
Opened 2021-02-04 20:10 UTC by ivanjiang5628

> **INSTRUCTIONS**
> Please make your PR readme as readable as possible. Only keep parts of this template that are filled out and meaningful to the reviewer.
>
> - Remove any quoted parts of the template below `>`. (These are just instructions for you to follow)
> - Leave all headings, but clear content and mark as `N/A` if irrelevant.
> - Most importantly: explain the "WHY". Do your best to give the reviewer some context about this change.

## Description
- [Jira Ticket](https://janeapp.atlassian.net/browse/...)

> Provide a summary of the problem being solved, the work done, and what was added/removed/changed

### General PR Class
🐛 = Bug Fix (Fixes an Issue)
🌟 = New Feature (Adds Functionality)
🏇 = Performance improvement
👁 = UX / UI improvement
🏗 = Refactor
🌦 = Env Changes
☕️ = JS Dependency Changes
⚛️ = Jane Desktop Changes

### Release Note
> Describe here a CS friendly version of what this fixes/adds. If the change is behind a feature flag, please include that in your description. If this is a hidden change CS doesn't need to really know about then just say so.

### Dependencies / ENV
> Describe any dependencies or ENV variables that are required for this change. Notify the team, if they have to update their environment.

### Risk Scorecard
> 1. As the author you should check the boxes that correspond with your PR and then use the following guide to set your risk label:
> * 0 checkboxes => low risk
> * 1-3 checkboxes => medium risk
> * 4+ checkboxes => high risk
> 2. Unless exempt, checked risk factors should be explained comprehensively in the Release Risk Assessment section below
> 3. Medium or higher risk PRs should get more than one code-review approval
>
> NOTE: if you aren't changing any production files, please use the zero risk label

- [ ] requires env configuration to be added in production
- [ ] js package changes<sup>1</sup>
- [ ] more than 200 LOC changed in production files<sup>1</sup>
- [ ] includes a user-facing workflow change to an existing production feature (user muscle memory or pattern recognition will be affected)
- [ ] could prevent access to Jane Video (eg. cors, middleware, changes to auth system)
- [ ] affects a widely used component or piece of code
- [ ] I have a doubt - I want the RMT to review this. If possible, please elaborate your concerns in the risk assessment section.

<sup>1</sup> No need to explain these risk factors below

### Release Risk Assessment
> Describe what areas of Jane are touched by the change in this PR, and what it would look like if something were to go wrong, and how much damage could be done. Keep your neighborhood deployer in mind when filling in this section, it will help identify errant PRs more quickly during deploy.

### Demo Notes
> If you have instructions on how to demo or a video add it here

## Code Review
Resource: [Dev Team Notion Page](https://www.notion.so/janeapp/Dev-Team-f06c6eb2ccca4066bc63fc1ac1bd2549)
Resource: [Code Review Checklist](https://www.notion.so/janeapp/Code-Review-checklist-2c510c527ac7470c902a5e8f25f9db3c)

- [ ] I clearly explained the WHY behind the work, in the Description above

#### Design
- [ ] I added instructions for how to test, in the QA section below
- [ ] I added specs for changes, or determined that none were required
- [ ] I demoed this to the appropriate person
- [ ] I considered both mobile & desktop views, or that wasn't relevant

#### Code
- [ ] I committed code with informative git messages
- [ ] I wrote readable code, or added comments if it was complex
- [ ] I performed a self-review of my own code
- [ ] I rebased my branch on the latest `master`

## QA and Smoke Testing
### Steps to Reproduce
> - Add steps on how to reproduce the problem and how to test
> - ie. Create Appointment > Clicked Arrived > Pay > Look for "this"

### Fixed / Expected Behaviour
> - What new behaviour does QA and Review need to look out for?

### Jane Desktop
> - Should these changes be tested in Jane Desktop? If the PR touches any of the [areas outlined here](https://www.notion.so/janeapp/Jane-Desktop-a10c9c06b180487982a3ef67d6163db9#9ea43281537e458089a87229e7281612), the answer is probably yes. If yes, indicate which areas.
> - How to test [video-chat inside Jane Desktop locally is outlined here](https://github.com/janeapp/jane_electron/blob/master/README.md#testing-video-chat)

### Other Considerations
> - Will this affect other parts of the app or views?
> - How can the success of this work be confirmed after release to production?
> - What QA have you already done?

## Screenshots
### Before
### After

2021-02-05 22:04 UTC, climbingcode approved these changes
Nice use of the dispatcher here for Screen changes

2021-02-05 22:57 UTC, ivanjiang5628 commented on react/features/welcome/components/WelcomeScreenButton.js
> +
You are right! I will make a reusable `JaneButton` component.

2021-02-08 17:34 UTC, climbingcode commented on react/features/welcome/components/Screen/Screens.js
> +                onPress = { onPressRedirectTo('staff', props.dispatch) }
Nice, I wonder if we can use the closure though to keep the props in memory. So we don't have to keep passing the dispatch

```
 const setUpRedirectTo = (dispatch) => (pathname) => dispatch(pathname)
 
 const Component = (props) => {
     const redirectTo = setUpRedirectTo(props.dispatch)
     
     return (
        ... 
        redirectTo('staff')
 } 
```

2021-02-08 17:35 UTC, climbingcode approved these changes

2021-02-08 21:32 UTC, gerbus reviewed
Thanks Ivan. I took a look and had a few thoughts.

This is about 1300 lines of code to review, which is a lot and inevitably going to get less review coverage than a smaller PR would get, which implies more risk. I think we really need to start breaking up these PRs into smaller parts. For example, here I think we could have done a PR for the new Screen component itself, and a second PR to wire it up for use. Maybe even a small PR to split out the new JaneButton.

Even if we were to release them all at once, it will be better for reviews, and get us into the practice of thinking through a feature's development/release before coding it. I know the team doesn't really have this baked into the process right now, but I'm hoping once we start using "cycles" I can help dig into features with you and the team and work on that.

2021-02-08 21:32 UTC, gerbus commented on react/features/welcome/components/Indicator.js
> +        return null;
I wonder if we want to throw some logging somewhere for these kinds of things. If somewhere in the code we use <Indicator> without specifying `count`, we probably want to know that in dev instead of just returning `null` which can be confusing while developing. Not important here, but I wonder if it could be a good idea going forward.

2021-02-08 21:32 UTC, gerbus commented on react/features/welcome/components/Screen/styles.js
> +    bigText: {
Do we not want to have this somewhere even more common than just in `/components/Screen`? Just feels weird to be setting this to `commonStyles` and have it be folder-scoped just to this component, since it feels more like an app-wide style. Same with a few others below.

2021-02-08 21:34 UTC, gerbus commented
Also, in janeapp/jane we consider most PRs with more than 200 lines of code changed to be medium risk. Why do you think this is low risk @ivanjiang5628? Would be good to document that context in the PR documentation.

2021-02-09 16:54 UTC, gerbus approved these changes

2021-02-09 16:54 UTC, gerbus commented on react/features/base/styles/functions.native.js
> +}
Great! Much more straight-forward 👍🏻

2021-02-09 16:54 UTC, gerbus commented on react/features/base/styles/functions.native.js
> +    });
🎉

2021-02-11 21:44 UTC, clem-jane commented
@jngo-janeapp could we get your help to QA this?

2021-02-11 23:00 UTC, jngo-janeapp commented
## Before Testing
- [ ] CI must be passing
- [ ] No conflicts
- [ ] No unresolved reviews/changes requested
- [ ] No additional changes/pushes from dev since the last round of QA
- [ ] Release note is sufficient for [#features](https://janeapp.slack.com/archives/C0KC1395G)
- [ ] Read through Notion / Jira story / Linear Issue / Slack Convo / Demo video
- [ ] Read through comments

## Developer's Recommended Test Plan
- [ ] TBD

## Additional Thoughts on Testing
- [ ] TBD

## Mobile, Browsers, Jane Desktop
- [ ] Google Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Microsoft Edge
- [ ] iPad Mini
- [ ] iPhone

## Regression Testing / Exploratory
(Consider related areas or areas where data persists Ie. Chart Templates/Intake Forms, Chart Entries/Export to PDF, Reports / Export to CSV/xls, Payment / Receipts / Superbill(US))
- Can you export a PDF from this area/function?
- Can this functionality be reused somewhere else in Jane? Or does it share components with other areas in Jane. (Canadian & US Insurance)
- Does this area have an inverse setting? Enabled/Disabled, Beta Feature Flag
- When testing emails: Have you tested both with an email on file and with no email on file, manually triggered emails (Welcome, Password Reset, Intake Form, Upcoming Appointments) and automated emails: Thanks for Booking, Cancelations, Reminders, Surveys, Telehealth, R&R, and RVR. Also, have you tried to trigger Family Relationship emails?
- Does this area have multiple setting types? Ie. Intake Forms, Permissions/Privacy, User types
- Does this correspond to an area in Online Booking? (Booking an appointment, Entering a credit card and paying for an appointment)
- Is this related to Payment Methods? Jane Payments: Stripe, Payfirma, Square Terminal, Cash, Gift Cards, Credit Memos, Account Credit, Packages
- Could this be affected by Family Relationships?
- Could data be affected by Merging Patient Profiles?
- Could data be affected by rebooking/canceling appointments or changing treatments?
- Can this be Created, Viewed, Updated, Archived/Unarchived or Deleted? (CRUD Test)
- Activity Report?
- Trigger a validation Error?
- Should we test different Staff Member Permissions and SU?
- Does this change functionality where existing data or settings may be affected? Might we need to create existing data/settings and then deploy the PR to the sandbox to see how it behaves to replicate how a real-life account might experience the change?

## Pass Story on QA Board / Mark Done in Jira/ Mark Scheduled for Release in Linear
- [ ] LGTM

## Move PR on Roll Out Board
- [ ] Moved from **QA** to **Patch Release Candidate**

2021-02-12 16:27 UTC, jngo-janeapp commented
hey @ivanjiang5628 @clem-jane when testing this on my ipad the spacing for text is overlapping with the video and other text. 
![Image from iOS (31)](https://user-images.githubusercontent.com/68558703/107794226-053f4600-6d0c-11eb-9d52-c9ba443799fd.png)
![Image from iOS (32)](https://user-images.githubusercontent.com/68558703/107794231-07a1a000-6d0c-11eb-83a8-6e40b4c6c64b.png)
![Image from iOS (33)](https://user-images.githubusercontent.com/68558703/107794241-0a03fa00-6d0c-11eb-89cd-3ae4e95d5524.png)
![Image from iOS (34)](https://user-images.githubusercontent.com/68558703/107794252-0e301780-6d0c-11eb-8a3d-3861d3430cc1.png)
![Image from iOS (35)](https://user-images.githubusercontent.com/68558703/107794259-112b0800-6d0c-11eb-98c6-2387828fd125.png)
![Image from iOS (37)](https://user-images.githubusercontent.com/68558703/107794271-14be8f00-6d0c-11eb-820a-9cda46cbf2cc.png)

2021-02-12 17:49 UTC, clem-jane commented
@jngo-janeapp Nice catch on the iPad. Which iPad is this so @ivanjiang5628  can recreate? Was this happening with all iPads including the iPad Pro, or just the iPad Mini?

2021-02-12 18:17 UTC, jngo-janeapp commented
> @jngo-janeapp Nice catch on the iPad. Which iPad is this so @ivanjiang5628 can recreate? Was this happening with all iPads including the iPad Pro, or just the iPad Mini?

hey @clem-jane its currently happening on my ipad mini ios 14.4 ! it appears to be fine on the simulator after speaking with Ivan, while testing the physical device its not displaying as expected.

2021-02-12 21:16 UTC, clem-jane commented
> hey @clem-jane its currently happening on my ipad mini ios 14.4 ! it appears to be fine on the simulator after speaking with Ivan, while testing the physical device its not displaying as expected.

Good thing you caught this before we pushed this out. We'll go another round once @ivanjiang5628 's addressed this when he gets back.

2021-02-12 22:10 UTC, gerbus commented
> > @jngo-janeapp Nice catch on the iPad. Which iPad is this so @ivanjiang5628 can recreate? Was this happening with all iPads including the iPad Pro, or just the iPad Mini?
> 
> hey @clem-jane its currently happening on my ipad mini ios 14.4 ! it appears to be fine on the simulator after speaking with Ivan, while testing the physical device its not displaying as expected.

Yeah there are some consistent differences between the simulator and real devices. Jane might want to consider getting some devices where those differences are well established. Something to think about if we want to be really confident across devices.

2021-02-16 20:08 UTC, climbingcode approved these changes
This code all makes sense. However, are we sure that disabling the font scaling is the right move here 🤔  as It's needed for accessibility? Wondering if we need a fixed height on the Text? Do we not want to grow the text past the screen bottom (scrollable view)?

2021-02-17 19:19 UTC, ivanjiang5628 commented
After discussion with Clem, we have decided to disable the font scaling for IOS system accessibility on the welcome pages. We can do a follow-up PR to enable the scaling in the future if needed. @jinnyhuang Could you do another round of QA for this build? Thanks

2021-02-17 19:25 UTC, jinnyhuang commented
@ivanjiang5628 You might have tagged the wrong person?

2021-02-17 19:37 UTC, ivanjiang5628 commented
> @ivanjiang5628 You might have tagged the wrong person? 😅

LOL my bad, tagged the wrong person😢

2021-02-18 20:01 UTC, jngo-janeapp commented
hey @ivanjiang5628 @clem-jane looks good to me ! tested this on both my iphone and ipad mini ✅ 
![Image from iOS (39)](https://user-images.githubusercontent.com/68558703/108414360-fe6b7400-71e0-11eb-9740-d1c827fbbd95.png)
![Image from iOS (38)](https://user-images.githubusercontent.com/68558703/108414367-ff9ca100-71e0-11eb-9bc7-191bf9820aff.png)

2021-02-23 16:17 UTC, gerbus requested changes
I looked at 63455c28c62be912e165f499d3c3113016c263c8 and only had one thought. Otherwise additional changes look good.

2021-02-23 16:17 UTC, gerbus commented on react/features/base/react/components/native/ScaledText.js
> +export default function ScaledText(props: Props) {
It's maybe just a little confusing to call this component "ScaledText" since it's behavior is to disable font scaling.. Would this make more sense called "FixedScaleText" maybe @ivanjiang5628 ?

2021-02-23 23:56 UTC, gerbus approved these changes

2021-02-24 18:10 UTC, merged